{
 "title": "BPF Performance - Windows 2019",
 "time": { "from": "2023-09-08T22:54:41.500Z", "to": "2023-09-09T03:03:11.500Z" },
 "panels": [
  {
   "title": "eBPF For Windows - Server 2019 - Helpers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value as Baseline FROM benchmarkresults WHERE (metric = 'Baseline' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as bpf_get_prandom_u32 FROM benchmarkresults WHERE (metric = 'bpf_get_prandom_u32' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as bpf_xdp_adjust_head_zero FROM benchmarkresults WHERE (metric = 'bpf_xdp_adjust_head_zero' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as bpf_xdp_adjust_head_positive FROM benchmarkresults WHERE (metric = 'bpf_xdp_adjust_head_positive' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as bpf_xdp_adjust_head_negative FROM benchmarkresults WHERE (metric = 'bpf_xdp_adjust_head_negative' AND platform = 'windows-2019') LIMIT 50 "
    }
   ]
  },
  {
   "title": "eBPF For Windows - Server 2019 - BPF_MAP_TYPE_ARRAY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_ARRAY read\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_ARRAY read' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_ARRAY update\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_ARRAY update' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_ARRAY replace\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_ARRAY replace' AND platform = 'windows-2019') LIMIT 50 "
    }
   ]
  },
  {
   "title": "eBPF For Windows - Server 2019 - BPF_MAP_TYPE_PERCPU_ARRAY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_PERCPU_ARRAY read\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_PERCPU_ARRAY read' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_PERCPU_ARRAY update\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_PERCPU_ARRAY update' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_PERCPU_ARRAY replace\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_PERCPU_ARRAY replace' AND platform = 'windows-2019') LIMIT 50 "
    }
   ]
  },
  {
   "title": "eBPF For Windows - Server 2019 - BPF_MAP_TYPE_HASH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_HASH read\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_HASH read' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_HASH update\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_HASH update' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_HASH replace\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_HASH replace' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_HASH update and read\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_HASH update and read' AND platform = 'windows-2019') LIMIT 50 "
    }
   ]
  },
  {
   "title": "eBPF For Windows - Server 2019 - BPF_MAP_TYPE_PERCPU_HASH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_PERCPU_HASH read\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_PERCPU_HASH read' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_PERCPU_HASH update\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_PERCPU_HASH update' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_PERCPU_HASH replace\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_PERCPU_HASH replace' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_PERCPU_HASH update and read\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_PERCPU_HASH update and read' AND platform = 'windows-2019') LIMIT 50 "
    }
   ]
  },
  {
   "title": "eBPF For Windows - Server 2019 - BPF_MAP_TYPE_LRU_HASH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LRU_HASH read\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LRU_HASH read' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LRU_HASH update\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LRU_HASH update' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LRU_HASH replace\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LRU_HASH replace' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LRU_HASH update and read\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LRU_HASH update and read' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LRU_HASH rolling update\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LRU_HASH rolling update' AND platform = 'windows-2019') LIMIT 50 "
    }
   ]
  },
  {
   "title": "eBPF For Windows - Server 2019 - BPF_MAP_TYPE_LPM_TRIE_1K",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LPM_TRIE_1K read\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LPM_TRIE_1K read' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LPM_TRIE_1K update\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LPM_TRIE_1K update' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LPM_TRIE_1K replace\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LPM_TRIE_1K replace' AND platform = 'windows-2019') LIMIT 50 "
    }
   ]
  },
  {
   "title": "eBPF For Windows - Server 2019 - BPF_MAP_TYPE_LPM_TRIE_16K",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LPM_TRIE_16K read\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LPM_TRIE_16K read' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LPM_TRIE_16K update\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LPM_TRIE_16K update' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LPM_TRIE_16K replace\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LPM_TRIE_16K replace' AND platform = 'windows-2019') LIMIT 50 "
    }
   ]
  },
  {
   "title": "eBPF For Windows - Server 2019 - BPF_MAP_TYPE_LPM_TRIE_256K",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LPM_TRIE_256K read\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LPM_TRIE_256K read' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LPM_TRIE_256K update\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LPM_TRIE_256K update' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LPM_TRIE_256K replace\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LPM_TRIE_256K replace' AND platform = 'windows-2019') LIMIT 50 "
    }
   ]
  },
  {
   "title": "eBPF For Windows - Server 2019 - BPF_MAP_TYPE_LPM_TRIE_1M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LPM_TRIE_1M read\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LPM_TRIE_1M read' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LPM_TRIE_1M update\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LPM_TRIE_1M update' AND platform = 'windows-2019') LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", value as \"BPF_MAP_TYPE_LPM_TRIE_1M replace\" FROM benchmarkresults WHERE (metric = 'BPF_MAP_TYPE_LPM_TRIE_1M replace' AND platform = 'windows-2019') LIMIT 50 "
    }
   ]
  }
 ]
}