# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

tests:
  - name: Baseline
    description: The Baseline test with an empty eBPF program.
    elf_file: baseline.o
    iteration_count: 10000000
    program_cpu_assignment:
      baseline_program: all

  - name: Baseline - no_batching
    description: The Baseline test with an empty eBPF program.
    elf_file: baseline.o
    batch_size: 1
    iteration_count: 10000000
    program_cpu_assignment:
      baseline_program: all

  - name: Hash-table Map Read
    description: Tests reading from a BPF_MAP_TYPE_HASH map.
    elf_file: generic_map.o
    map_state_preparation:
      program: prepare_HASH_state_generic_read
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      read_HASH: all

  - name: Hash-table Map Update
    description: Tests writing to a BPF_MAP_TYPE_HASH map.
    elf_file: generic_map.o
    map_state_preparation:
      program: prepare_HASH_state_generic_read
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      update_HASH: all

  - name: Hash-table Map Update / Read
    description: Tests reading and writing to a BPF_MAP_TYPE_HASH map.
    elf_file: generic_map.o
    map_state_preparation:
      program: prepare_HASH_state_generic_read
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      update_HASH: [0]
      read_HASH: remaining

  - name: Per-CPU Hash-table Map Read
    description: Tests reading from a BPF_MAP_TYPE_PERCPU_HASH map.
    elf_file: generic_map.o
    map_state_preparation:
      program: prepare_PERCPU_HASH_state_generic_read
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      read_PERCPU_HASH: all

  - name: Per-CPU Hash-table Map Update
    description: Tests writing to a BPF_MAP_TYPE_PERCPU_HASH map.
    elf_file: generic_map.o
    map_state_preparation:
      program: prepare_PERCPU_HASH_state_generic_read
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      update_PERCPU_HASH: all

  - name: Per-CPU Hash-table Map Update / Read
    description: Tests reading and writing to a BPF_MAP_TYPE_PERCPU_HASH map.
    elf_file: generic_map.o
    map_state_preparation:
      program: prepare_PERCPU_HASH_state_generic_read
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      update_PERCPU_HASH: [0]
      read_PERCPU_HASH: remaining

  - name: Array Map Read
    description: Tests reading from a BPF_MAP_TYPE_ARRAY map.
    elf_file: generic_map.o
    map_state_preparation:
      program: prepare_ARRAY_state_generic_read
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      read_ARRAY: all

  - name: Array Map Update
    description: Tests writing to a BPF_MAP_TYPE_ARRAY map.
    elf_file: generic_map.o
    map_state_preparation:
      program: prepare_ARRAY_state_generic_read
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      update_ARRAY: all

  - name: Per-CPU Array Map Read
    description: Tests reading from a BPF_MAP_TYPE_PERCPU_ARRAY map.
    elf_file: generic_map.o
    map_state_preparation:
      program: prepare_PERCPU_ARRAY_state_generic_read
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      read_PERCPU_ARRAY: all

  - name: Per-CPU Array Map Update
    description: Tests writing to a BPF_MAP_TYPE_PERCPU_ARRAY map.
    elf_file: generic_map.o
    map_state_preparation:
      program: prepare_PERCPU_ARRAY_state_generic_read
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      update_PERCPU_ARRAY: all


  - name: LRU Hash-table Map Read
    description: Tests reading from a BPF_MAP_TYPE_LRU_HASH map.
    elf_file: generic_map.o
    map_state_preparation:
      program: prepare_LRU_HASH_state_generic_read
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      read_LRU_HASH: all

  - name: LRU Hash-table Map Update
    description: Tests writing to a BPF_MAP_TYPE_LRU_HASH map.
    elf_file: generic_map.o
    map_state_preparation:
      program: prepare_LRU_HASH_state_generic_read
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      update_LRU_HASH: all

  - name: LRU Hash-table rolling update
    description: Tests reading and writing to a BPF_MAP_TYPE_LRU_HASH map with a rolling key.
    elf_file: rolling_lru.o
    map_state_preparation:
      program: prepare_rolling_lru_state
      iteration_count: 8192
    iteration_count: 10000000
    program_cpu_assignment:
      read_or_update_rolling_lru: all

  - name: bpf_get_prandom_u32
    description: Tests the bpf_get_prandom_u32 helper.
    elf_file: helpers.o
    iteration_count: 10000000
    program_cpu_assignment:
      test_bpf_get_prandom_u32: all

  - name: BPF_MAP_TYPE_ARRAY_OF_MAPS read
    description: Test BPF_MAP_TYPE_ARRAY_OF_MAPS
    elf_file: map_in_map.o
    map_state_preparation:
      program: prepare_map_in_map
      iteration_count: 8192
    iteration_count: 10000000
    program_cpu_assignment:
      read_map_in_map: all

  - name: BPF_MAP_TYPE_ARRAY_OF_MAPS update
    description: Test BPF_MAP_TYPE_ARRAY_OF_MAPS
    elf_file: map_in_map.o
    map_state_preparation:
      program: prepare_map_in_map
      iteration_count: 8192
    iteration_count: 10000000
    program_cpu_assignment:
      write_map_in_map: all

  - name: bpf_tail_call
    description: Tests the bpf_tail_call helper.
    elf_file: tail_call.o
    iteration_count: 10000000
    program_cpu_assignment:
      test_bpf_tail: all

  - name: bpf_xdp_adjust_head_0
    description: Tests the bpf_xdp_adjust_head helper with a zero offset.
    program_type: xdp
    elf_file: xdp.o
    iteration_count: 10000000
    program_cpu_assignment:
      test_bpf_xdp_adjust_head_0: all

  - name: bpf_xdp_adjust_head_plus_100
    description: Tests the bpf_xdp_adjust_head helper with a positive offset.
    program_type: xdp
    elf_file: xdp.o
    iteration_count: 10000000
    program_cpu_assignment:
      test_bpf_xdp_adjust_head_plus_100: all

  - name: bpf_xdp_adjust_head_minus_100
    description: Tests the bpf_xdp_adjust_head helper with a negative offset.
    program_type: xdp
    elf_file: xdp.o
    iteration_count: 10000000
    program_cpu_assignment:
      test_bpf_xdp_adjust_head_minus_100: all

  - name: BPF_MAP_TYPE_LPM_TRIE_1024
    description: Tests the BPF_MAP_TYPE_LPM_TRIE map type.
    elf_file: lpm.o
    map_state_preparation:
      program: prepare_lpm_state_1024
      iteration_count: 1024
    iteration_count: 10000000
    program_cpu_assignment:
      read_lpm_1024: all

  - name: BPF_MAP_TYPE_LPM_TRIE_16384
    description: Tests the BPF_MAP_TYPE_LPM_TRIE map type.
    elf_file: lpm.o
    map_state_preparation:
      program: prepare_lpm_state_16384
      iteration_count: 16384
    iteration_count: 10000000
    program_cpu_assignment:
      read_lpm_16384: all

  - name: BPF_MAP_TYPE_LPM_TRIE_262144
    description: Tests the BPF_MAP_TYPE_LPM_TRIE map type.
    elf_file: lpm.o
    map_state_preparation:
      program: prepare_lpm_state_262144
      iteration_count: 262144
    iteration_count: 10000000
    program_cpu_assignment:
      read_lpm_262144: all

  - name: BPF_MAP_TYPE_LPM_TRIE_1048576
    description: Tests the BPF_MAP_TYPE_LPM_TRIE map type.
    elf_file: lpm.o
    map_state_preparation:
      program: prepare_lpm_state_1048576
      iteration_count: 1048576
    iteration_count: 10000000
    program_cpu_assignment:
      read_lpm_1048576: all

  # Add more test cases as needed
